Select * from customer limit 20;

--Q1. What is the total revenue generated by male vs. female customers?

Select gender , sum(purchase_amount) as revenue
from customer
group by gender;

--Q2. Which customers used a discount but still spent more then the average purchase amount?

Select  customer_id , purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount > (Select avg(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased 
from customer
where review_rating > (Select avg(review_rating) from customer)
limit 5;

Select item_purchased , ROUND(avg(review_rating ::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average purchase amounts between standard and express shiping.

Select shipping_type , 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--    subscribers and non-subscribers.

Select subscription_status , 
COUNT(customer_id) as total_customers ,
ROUND(avg(purchase_amount),2) as avg_spend,
ROUND(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue , avg_spend desc;


--Q6. Which 5 products have the  highest percentage of purchases with discounts applied?

Select item_purchased , 
ROUND(100 * sum(case when discount_applied = 'Yes'  THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New,Returning,and Loyal based on their
--    total number of previous purchases ,and show the count of each segment?

with customer_type as(
Select customer_id ,previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
Select customer_segment , count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category ?


Select category , count(*) as "No. of times purchased"
from customer
group by  category
limit 3;

with item_counts as(
Select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

Select item_rank , category,item_purchased , total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

Select subscription_status ,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

Select age_group , sum(purchase_amount) as tot_revenue
from customer
group by age_group
order by tot_revenue desc;


